# plans/_index.yaml - Agent navigation manifest
# PURPOSE: Feature planning documents and specifications

purpose: "Feature plans, specifications, and implementation tracking"

triggers:
  - "feature plan"
  - "specification"
  - "what are we building"
  - "implementation plan"
  - "backlog"
  - "work items"

directories:
  - path: "001-hello-world-baseline/"
    summary: "Minimal scaffolding to prove build pipeline works (Go + Vite + Electron)"
    keywords: [baseline, hello-world, scaffolding, build, setup]
    status: planned
    complexity: CS-2
    issue: 13

  - path: "009-url-routing/"
    summary: "URL-based session state for shareable/bookmarkable terminal workspaces"
    keywords: [url, routing, state, sharing, bookmarks, sessions]
    status: planned
    complexity: CS-2
    issue: 27

  - path: "010-github-oauth/"
    summary: "GitHub OAuth authentication for secure remote access with user allowlist"
    keywords: [oauth, github, authentication, security, remote-access, authorization]
    status: planned
    complexity: CS-4
    issue: 28

files:
  - path: "001-hello-world-baseline/hello-world-baseline-spec.md"
    summary: "Feature specification with goals, acceptance criteria, clarifications"
    keywords: [spec, requirements, acceptance-criteria]

  - path: "001-hello-world-baseline/hello-world-baseline-plan.md"
    summary: "Implementation plan with 25 tasks, research findings, task dependencies"
    keywords: [plan, tasks, implementation, research]

  - path: "009-url-routing/research-dossier.md"
    summary: "Research synthesis from 7 investigation tracks on URL state management"
    keywords: [research, url, zustand, vite, next.js, routing]

  - path: "009-url-routing/url-routing-spec.md"
    summary: "Feature specification for URL-based session state sharing"
    keywords: [spec, url, sessions, bookmarks, sharing]

  - path: "009-url-routing/url-routing-plan.md"
    summary: "Simple mode implementation plan with 9 tasks for URL session state"
    keywords: [plan, tasks, implementation, url, sessions]

  - path: "010-github-oauth/research-dossier.md"
    summary: "Research synthesis for GitHub OAuth integration with architecture analysis"
    keywords: [research, oauth, github, authentication, websocket, jwt]

  - path: "010-github-oauth/github-oauth-spec.md"
    summary: "Feature specification for GitHub OAuth with acceptance criteria and complexity analysis"
    keywords: [spec, oauth, github, authentication, security, remote-access]

  - path: "010-github-oauth/github-oauth-plan.md"
    summary: "7-phase implementation plan for GitHub OAuth with TDD tasks and risk mitigations"
    keywords: [plan, oauth, github, authentication, tdd, phases, tasks]
